### ISSUE TITLE
Add ability to exclude all transitive dependencies from feature's projects

### ISSUE THREAD

**Issue by SOVALINUX** [lburgazzoli/gradle-karaf-features-plugin#11]
Hi, 
First of all want to say thank you about amount of work you made.
However, is there any possibility to exclude all transitive dependencies for project?

I have the following in the build.gradle
```
karafFeatures {
  featuresName = 'test-feature'
  repositories = ['some-repo']
  features {
    feature1 {
      name = "test-feature"
      description = "test-feature"
      version = "${project.version}"
    }
  }
}

subprojects.findAll {
  karafFeatures.features.feature1.project(it)
}
```

And want to get something like this in feature.xml
```
...
  <feature description='test-feature' name='test-feature' version='0.1.0'>
    <bundle>mvn:group/subProject1Name/0.1.0</bundle>
    <bundle>mvn:group/subProject2Name/0.1.0</bundle>
    <bundle>mvn:group/subProject3Name/0.1.0</bundle>
  </feature>
```
but now I'm having all transitive dependencies as the same bundle declarations
I tried to exclude them with bundle instructions, but there is no such flexibility I found right now.

So, is it possible to do it with current codebase or I should add some functionality?
I'm looking on BundleMatcher to be a victim for extending flexibility, but I feel that it's not the best choice

Thank you in advance

**Comment by lburgazzoli** [comment]
I need to check deeply but I'm a little busy at the moment so I cannot tell you by when I could give you an answer so if you want to send a PR to improve the plugin or document its behavior it would more than welcome.

**Comment by SOVALINUX** [comment]
Okay then, I'll try to do it locally and in case of success submit PR:)

**Comment by SOVALINUX** [comment]
Thank you. I'm closing this issue
