### ISSUE TITLE
Create Kar archive based on features file

### ISSUE THREAD

**Issue by eschizoid** [lburgazzoli/gradle-karaf-features-plugin#18]
Add a Gradle task for creating Kar files.

**Comment by lburgazzoli** [comment]
This is my next activity, do you maybe have any code ready to be merged ?

**Comment by eschizoid** [comment]
Not really, sorry. But this the only project that we can't fully migrate to gradle because we rely on the `karaf-maven-plugin`.

**Comment by lburgazzoli** [comment]
I'm currently reviewing the plugin, I think I will start working on KAR end of next week

**Comment by eschizoid** [comment]
@lburgazzoli These are great news! Let me know and I can start testing as soon as you have something.

**Comment by lburgazzoli** [comment]
Could you have a look at version 2.9.10-SNAPSHOT ? I've added basic support for KARs

**Comment by eschizoid** [comment]
@lburgazzoli Sure thing, let me give a shot.

**Comment by lburgazzoli** [comment]
Sonatype OSS (https://oss.sonatype.org/content/repositories/snapshots)

**Comment by lburgazzoli** [comment]
@eschizoid does it work ?

**Comment by eschizoid** [comment]
@lburgazzoli seems to be fine.

**Comment by lburgazzoli** [comment]
great, can you close this issue if current KAR support is good enough for you ?
