### ISSUE TITLE
Karaf Kar Task creates jars with the file path as the contents

### ISSUE THREAD

**Issue by cetra3** [lburgazzoli/gradle-karaf-features-plugin#32]
Using version 2.9.10,

If you do the `generateKarafKar` it will create a kar, but instead of including the binary jar, it will instead create a file with the contents equal to the file path.

I.e the `commons-lang3-3.4.jar`:
```
cat repository/org.apache.commons/commons-lang3/3.4/commons-lang3-3.4.jar
/Users/cetra/.gradle/caches/modules-2/files-2.1/org.apache.commons/commons-lang3/3.4/5fe28b9518e58819180a43a850fbc0dd24b7c050/commons-lang3-3.4.jar
```

**Comment by lburgazzoli** [comment]
This plugin is not more maintained, please have a look at https://github.com/lburgazzoli/gradle-karaf-plugin
